### ISSUE TITLE
Crash on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [x-hgg-x/arkanoid-go#1]
Thank you for using Ebiten! I tested this but found a crash:

```
$ go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4150f4e]

goroutine 5 [running]:
github.com/hajimehoshi/ebiten.(*Image).isDisposed(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/image.go:57
github.com/hajimehoshi/ebiten.(*Image).Bounds(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/image.go:375
github.com/hajimehoshi/ebiten.(*Image).Size(...)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/image.go:52
arkanoid/systems/sprite.drawImageWithWrap(0xc000024580, 0xc00000e3e0)
        /Users/hajimehoshi/ebiten-games/arkanoid-go/systems/sprite/render.go:51 +0x6e
arkanoid/systems/sprite.RenderSystem(0xc00006c360, 0xc000012a50, 0xc000010088, 0xc000024580)
        /Users/hajimehoshi/ebiten-games/arkanoid-go/systems/sprite/render.go:42 +0x2a8
main.game.Update(0xc00006c360, 0xc000012a50, 0xc000010088, 0xc000024580, 0x20, 0x30)
        /Users/hajimehoshi/ebiten-games/arkanoid-go/main.go:36 +0x95
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc000254080, 0xc000024580, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/imagedumper_desktop.go:106 +0x4e
github.com/hajimehoshi/ebiten.(*imageDumperGame).Update(0xc00000e500, 0xc000024580, 0x468a960, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/run.go:180 +0x44
github.com/hajimehoshi/ebiten.(*uiContext).update(0x466cb40, 0xc0001d6140, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/uicontext.go:262 +0x150
github.com/hajimehoshi/ebiten.(*uiContext).Update(0x466cb40, 0xc0001d6140, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/uicontext.go:239 +0xb4
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x4667f20, 0x441a0a0, 0x466cb40, 0xc0001d0001, 0xc000048668)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/internal/uidriver/glfw/ui.go:751 +0x1d9
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0x4667f20, 0x441a0a0, 0x466cb40, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/internal/uidriver/glfw/ui.go:797 +0xec
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0x4667f20, 0x441a0a0, 0x466cb40, 0x0, 0x0)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/internal/uidriver/glfw/ui.go:669 +0x232
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc000012ac0, 0xc00006c3c0, 0x4667f20, 0x441a0a0, 0x466cb40)
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/internal/uidriver/glfw/ui.go:535 +0xbc
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
        /Users/hajimehoshi/go/pkg/mod/github.com/hajimehoshi/ebiten@v1.11.0-alpha.4.0.20200219165351-5b7151595b12/internal/uidriver/glfw/ui.go:532 +0x154
exit status 2

```

**Comment by x-hgg-x** [comment]
Can you check if you have the texture images in ```assets/textures``` and can open them ?
They are on Git LFS so if you don't have it installed, you may have corrupted images.

For now I ignore errors when using ```ebiten.NewImageFromFile``` but I will process them in the next commit.

**Comment by hajimehoshi** [comment]
Thanks, this worked after `git lfs fetch` and `git lfs checkout`.
